# Generated by Django 3.2.3 on 2021-06-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='price_form',
        ),
    ]
